import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Movies Updated',
  description: 'Generated by create next app',
  icons: {
    icon: "./tony.png"
  }
}

export default function RootLayout({ children }) {
  return (
    <>
    <Head>
       <link rel="shortcut icon" href='./tony'/>
    </Head>
    <html lang="en">
      <body className={inter.className}>
        <nav className='px-10 pt-5'>
          <Link prefetch href="/" className='text-2xl font-bold' >Unnamedeth <span className='text-teal-500' >DB</span></Link>
        </nav>
        {children}
      </body>
    </html>
        </>
  )
}
